name: Deploy

on:
  workflow_run:
    workflows: 
      - "Build"
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Download Java build artifact
        uses: actions/download-artifact@v4
        with:
          name: jar-artifact
  
      - name: Download Vue build artifact
        uses: actions/download-artifact@v4
        with:
          name: assets-artifact

      - name: Copy files to VPS
        run: |
          scp -r ./assets-artifact/* ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }}:/dungeondecks
          scp -r ./jar-artifact/* ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }}:/dungeondecks
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
